export {
  canonicalInventoryManufacturerName, createInventoryManufacturerInputSchema, inventoryManufacturerListSchema,
  inventoryManufacturerSchema, inventoryProductDetailWithManufacturerSchema, inventoryProductSaveResultWithManufacturerSchema, inventoryProductWithManufacturerSchema,
  getInventoryProductWithManufacturerInputSchema, listInventoryManufacturersInputSchema, normalizeInventoryManufacturerName,
  saveInventoryProductWithManufacturerInputSchema, updateInventoryManufacturerInputSchema,
  type InventoryManufacturer, type UpdateInventoryManufacturerInput,
} from "../../functions/src/inventory/inventory-manufacturer-contract";
